apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-jobs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-jobs
  template:
    metadata:
      labels:
        app: api-jobs
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-api-jobs
          imagePullPolicy: Always
          name: main
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: api-config
          volumeMounts:
            - name: cache
              mountPath: /service/data
      volumes:
        - name: cache
          emptyDir: {}
