apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cli
  template:
    metadata:
      labels:
        app: api-cli
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-api-cli
          imagePullPolicy: Always
          name: api-cli
          env:
            ## Global config ##
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: NODE_ENV
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: DOMAIN
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: APP_URL
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: API_URL

            ## Api Config ##
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: MONGO_URI
            - name: POSTMARK_FROM
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: POSTMARK_FROM
            - name: POSTMARK_APIKEY
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: POSTMARK_APIKEY
            - name: UPLOADS_STORE
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: UPLOADS_STORE
            - name: UPLOADS_GCS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: UPLOADS_GCS_BUCKET
          volumeMounts:
            - name: jobs-cache
              mountPath: /workdir/data
      volumes:
        - name: jobs-cache
          emptyDir: {}
