apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-web
          imagePullPolicy: Always
          name: main
          env:
            ## Global config ##
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: NODE_ENV
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: DOMAIN
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: API_URL
          ports:
            - name: http-server
              containerPort: 2200
