version: 2.1

orbs:
  deploy:
    orbs:
      gcloud: circleci/gcp-cli@1.0.6
      gcr: circleci/gcp-gcr@0.0.2
      k8s: circleci/kubernetes@0.1.0

    commands:
      build-and-deploy:
        parameters:
          deployment:
            description: "The Kubernetes deployment name."
            type: string
          container:
            description: "The Kubernetes container name."
            type: string
          gcloud-service-key:
            description: The gcloud service key
            type: env_var_name
            default: GCLOUD_SERVICE_KEY
          google-project-id:
            description: The Google project ID to connect with via the gcloud CLI
            type: env_var_name
            default: GOOGLE_PROJECT_ID
          google-compute-zone:
            description: The Google compute zone to connect with via the gcloud CLI
            type: env_var_name
            default: GOOGLE_COMPUTE_ZONE
          registry-url:
            description: The GCR registry URL from ['', us, eu, asia].gcr.io
            type: string
            default: gcr.io
          image:
            description: A name for your docker image
            type: string
          tag:
            description: A docker image tag
            type: string
            default: "latest"
          path-to-dockerfile:
            description: The relative path to the Dockerfile to use when building image
            type: string
            default: "."
        steps:
          - checkout
          - gcr/gcr-auth:
              google-project-id: <<parameters.google-project-id>>
              google-compute-zone: <<parameters.google-compute-zone>>
          - gcloud/install
          - k8s/install
          - gcr/build-image:
              registry-url: <<parameters.registry-url>>
              google-project-id: <<parameters.google-project-id>>
              image: <<parameters.image>>
              tag: << parameters.tag >>
              path-to-dockerfile: <<parameters.path-to-dockerfile>>
          - gcr/push-image:
              registry-url: <<parameters.registry-url>>
              google-project-id: <<parameters.google-project-id>>
              image: <<parameters.image>>
              tag: <<parameters.tag>>
          - run: |
              gcloud container clusters get-credentials <<parameters.deployment>>
              kubectl set image deployment <<parameters.deployment>> <<parameters.container>>=<<parameters.image>>

jobs:
  diff_check:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Determine which projects have changed and trigger the builds
          command: |
            mkdir -p .services-metadata
            if [ -z $CIRCLE_TOKEN ]; then
              echo "NO CIRCLE_TOKEN found in the environment variables"
              echo "1. Under your CircleCI user settings, create a Personal API Token"
              echo "2. Under the CircleCI project settings, add an environment var CIRCLE_TOKEN with the personal API token"
              exit 1
            fi

            # Identify modified directories
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=completed&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`

            #first commit in a branch
            if [[ ${LAST_SUCCESSFUL_COMMIT} == "null" ]]; then
              COMMITS="origin/master"
            else
              COMMITS="${CIRCLE_SHA1}..${LAST_SUCCESSFUL_COMMIT}"
            fi


            for project in services/*/; do
              projectname=$(basename $project)
              if [[ $(git diff $COMMITS --name-status | grep "$projectname") ]]; then
                echo "${projectname} => $(git diff $COMMITS --name-status)"
                touch .services-metadata/${projectname}-changed
              fi
            done
      - persist_to_workspace:
          root: .
          paths:
            - .services-metadata

  api:
    working_directory: ~/project/services/api
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project/services/api
      - run:
          name: Check whether project changed
          command: |
            if ! [ -e .services-metadata/api-changed ]; then
              echo "stopping as nothing was changed"
              circleci-agent step halt
              exit 0
            fi
            echo "running"
            ls .services-metadata
            rm -rf .services-metadata
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command: |
            yarn test
      - deploy/build-and-deploy:
          deployment: standard-cluster-1
          container: api
          image: sharkbone_api
          path-to-dockerfile: ./services/api/

  web:
    working_directory: ~/project/services/web
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project/services/web
      - run:
          name: Check whether project changed
          command: |
            if ! [ -e .services-metadata/web-changed ]; then
              echo "stopping as nothing was changed"
              circleci-agent step halt
              exit 0
            fi
            echo "running"
            ls .services-metadata
            rm -rf .services-metadata
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command: |
            yarn test

workflows:
  tasks:
    jobs:
      - diff_check:
          filters:
            branches:
              only:
                - master
                - ci
      - api:
          requires:
            - diff_check
      - web:
          requires:
            - diff_check
