kubeContext: gke_bedrock-core_us-east1-c_cluster-helm

global:
  env: "production"
  mongo_db: "bedrock_production"
  app:
    domain: "bedrock.foundation"
    url: "https://bedrock.foundation"

jwt:
  secret: "meepmeep"

mongo:
  storage: 30Gi
