apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-api-cli
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bedrock-api-cli
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: bedrock-api-cli
        tier: backend
    spec:
      containers:
        - image: "{{ .Values.image.api_cli.name }}:{{ .Values.image.api_cli.tag }}"
          imagePullPolicy: Always
          name: bedrock-api-cli
          env:
            - name: NODE_ENV
              value: {{ .Values.global.env | quote }}
            - name: MONGO_URI
              value: "mongodb://mongo:27017/{{ .Values.global.mongo_db }}"
            - name: APP_DOMAIN
              value: {{ .Values.global.app.domain | quote }}
            - name: APP_URL
              value: {{ .Values.global.app.url | quote }}
            - name: POSTMARK_FROM
              value: {{ .Values.postmark.from | quote }}
            - name: POSTMARK_APIKEY
              value: {{ .Values.postmark.api_key | quote }}
            - name: UPLOADS_STORE
              value: {{ .Values.uploads.store | quote }}
            - name: UPLOADS_GCS_BUCKET
              value: {{ .Values.uploads.gcs_bucket | quote }}
          ports:
            - name: http-server
              containerPort: 2300
          volumeMounts:
            - name: cache
              mountPath: /service/data
      volumes:
        - name: cache
          emptyDir: {}
