apiVersion: v1
kind: Service
metadata:
  name: bedrock-api
  labels:
    app: bedrock-api
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 2300
      protocol: TCP
  selector:
    app: bedrock-api
