apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-api
          imagePullPolicy: Always
          name: main
          env:
            - name: ADMIN_EMAIL
              value: "admin@bedrock.foundation"
            - name: ADMIN_PASSWORD
              value: "password1"
            - name: JWT_SECRET
              value: "changeme1234"
            - name: UPLOADS_STORE
              value: "gcs"
            - name: UPLOADS_GCS_BUCKET
              value: "bedrock-staging-uploads"
          envFrom:
            - configMapRef:
                name: global-config
            - configMapRef:
                name: api-config
          ports:
            - name: http-server
              containerPort: 2300
          volumeMounts:
            - name: cache
              mountPath: /service/data
      volumes:
        - name: cache
          emptyDir: {}
