environments:
  staging:
    values:
    - envs/{{ .Environment.Name }}.yaml
  production:
    values:
    - envs/{{ .Environment.Name }}.yaml

helmDefaults:
  atomic: true
  cleanupOnFail: true

templates:
  releaseDefaults: &releaseDefaults
    values:
      - envs/{{ .Environment.Name }}.yaml
    kubeContext: {{ .Values.kubeContext }}

releases:
- name: elasticsearch
  chart: charts/data/elasticsearch
  <<: *releaseDefaults

- name: mongo
  chart: charts/data/mongo
  <<: *releaseDefaults

- name: api
  chart: charts/services/api
  <<: *releaseDefaults
  needs:
  - mongo
  - elasticsearch

- name: api-cli
  chart: charts/services/api-cli
  <<: *releaseDefaults
  needs:
  - mongo
  - elasticsearch
